# Generated by Django 5.0.6 on 2025-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('frameworks', models.CharField(max_length=300)),
                ('max_team_size', models.IntegerField()),
                ('last_submission_datetime', models.DateTimeField()),
                ('evaluation_criteria', models.TextField()),
            ],
        ),
    ]
