# Generated by Django 5.0.6 on 2025-02-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitor', '0002_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sample_testcases', models.TextField()),
                ('python_code_prefix', models.TextField(blank=True, null=True)),
                ('python_function_signature', models.TextField(blank=True, null=True)),
                ('python_main', models.TextField(blank=True, null=True)),
                ('cpp_code_prefix', models.TextField(blank=True, null=True)),
                ('cpp_function_signature', models.TextField(blank=True, null=True)),
                ('cpp_main', models.TextField(blank=True, null=True)),
                ('java_code_prefix', models.TextField(blank=True, null=True)),
                ('java_function_signature', models.TextField(blank=True, null=True)),
                ('java_main', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('frameworks', models.CharField(max_length=300)),
                ('max_team_size', models.IntegerField()),
                ('last_submission_datetime', models.DateTimeField()),
                ('evaluation_criteria', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('end_time', models.DateTimeField()),
                ('time_duration', models.PositiveIntegerField(help_text='Duration in hours')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_link', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.groupevent')),
                ('files', models.ManyToManyField(blank=True, to='host.file')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='host.groupevent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='competitor.team')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='host.problem')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualEventProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_problems', to='host.individualevent')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_events', to='host.problem')),
            ],
            options={
                'unique_together': {('individual_event', 'problem')},
            },
        ),
    ]
