# Generated by Django 5.0.6 on 2025-01-28 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0001_initial'),
        ('host', '0002_groupevent_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='host.groupevent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='competitor.team')),
            ],
        ),
    ]
