# Generated by Django 5.0.6 on 2025-02-23 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_file_projectsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sample_testcases', models.TextField()),
                ('python_code_prefix', models.TextField(blank=True, null=True)),
                ('python_function_signature', models.TextField(blank=True, null=True)),
                ('python_main', models.TextField(blank=True, null=True)),
                ('cpp_code_prefix', models.TextField(blank=True, null=True)),
                ('cpp_function_signature', models.TextField(blank=True, null=True)),
                ('cpp_main', models.TextField(blank=True, null=True)),
                ('java_code_prefix', models.TextField(blank=True, null=True)),
                ('java_function_signature', models.TextField(blank=True, null=True)),
                ('java_main', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='host.problem')),
            ],
        ),
    ]
