# Generated by Django 5.0.6 on 2025-02-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_problem_testcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('last_submission_datetime', models.DateTimeField()),
                ('time_duration', models.IntegerField(help_text='Duration in minutes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_events', to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(related_name='individual_events', to='host.problem')),
            ],
        ),
    ]
