# Generated by Django 5.0.6 on 2025-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_individualevent_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
