# Generated by Django 5.0.6 on 2025-03-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_alter_individualevent_start_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualevent',
            old_name='price',
            new_name='prize',
        ),
    ]
