# Generated by Django 5.0.6 on 2025-03-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0004_indresult'),
        ('host', '0010_rename_price_individualevent_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_quality', models.IntegerField(default=0)),
                ('innovation', models.IntegerField(default=0)),
                ('Security', models.IntegerField(default=0)),
                ('frontend', models.IntegerField(default=0)),
                ('functionality', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='host.groupevent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='competitor.team')),
            ],
        ),
    ]
