# Generated by Django 5.0.6 on 2025-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_rename_security_hackathongrading_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
